### ISSUE TITLE
ActiveModel

### ISSUE THREAD

**Issue by enricribas** [topofocus/active-orient#5]
It seems that you have a hard dependency on activemodel but don't list it in the gemspec?
Your example in the README doesn't work as is.

Unless I'm missing something. Had to add 'activemodel' gem as well

Thanks.

**Comment by topofocus** [comment]
Hi, 
can you please specify which error appeared? Problem is, that this gem is present in all my environments. 
The Idea is, to keep external references to the minimum. Rails specific libraries are huge and consume many resources. ActiveModel should not be necessary because anything is handled lightweight in OrientModel.

**Comment by enricribas** [comment]
Yes, I agree a dependency on ActiveModel would be unfortunate.
But the second line in lib/base.rb clearly requires 'active_model'
And your Gemfile list activemodel as well


```
gems/active-orient-0.41/lib/base.rb:2:in `require': cannot load such file -- active_model (LoadError)
```

**Comment by topofocus** [comment]
You are right, the dependency is missing in the gemspec,
I included it only in the Gemfile.

Activemodel is necessary, ActiveRecord is the resource-consuming gem which is omitted.
The dependency will be included in future releases.

**Comment by influitive-server** [comment]
Cool, thank you. Feel free to close.
